### ISSUE TITLE
TestDataPath_Key causes a SIGSEGV

### ISSUE THREAD

**Issue by eclipseo** [viant/assertly#3]
Fedora 32 with Go 1.14 beta1

```
Testing    in: /builddir/build/BUILD/assertly-0.5.3/_build/src
         PATH: /builddir/build/BUILD/assertly-0.5.3/_build/bin:/builddir/.local/bin:/builddir/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/assertly-0.5.3/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags "-X github.com/viant/assertly/version=0.5.3 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '"
      testing: github.com/viant/assertly
github.com/viant/assertly
--- FAIL: TestDataPath_Key (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x562473a4516e]

goroutine 35 [running]:
testing.tRunner.func1.1(0x562473b41100, 0x562473dd5a90)
	/usr/lib/golang/src/testing/testing.go:942 +0x3d2
testing.tRunner.func1(0xc000155560)
	/usr/lib/golang/src/testing/testing.go:945 +0x3fb
panic(0x562473b41100, 0x562473dd5a90)
	/usr/lib/golang/src/runtime/panic.go:967 +0x161
github.com/viant/assertly.(*dataPath).Key(0xc000137630, 0x562473a64192, 0x2, 0x256142c50000000f, 0x5e44a74a)
	/builddir/build/BUILD/assertly-0.5.3/_build/src/github.com/viant/assertly/path.go:63 +0x9e
github.com/viant/assertly.TestDataPath_Key(0xc000155560)
	/builddir/build/BUILD/assertly-0.5.3/_build/src/github.com/viant/assertly/path_test.go:10 +0x71
testing.tRunner(0xc000155560, 0x562473bacc80)
	/usr/lib/golang/src/testing/testing.go:993 +0xde
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1044 +0x359
exit status 2
FAIL	github.com/viant/assertly	0.022s
```

Not sure if this is linked to Go 1.14 or not.

**Comment by adranwit** [comment]
Thanks for raise the issue, it has been already patched
